distributed.nanny - INFO -         Start Nanny at: 'tcp://172.18.0.6:37987'
distributed.worker - INFO -       Start worker at:     tcp://172.18.0.6:35951
distributed.worker - INFO -          Listening to:     tcp://172.18.0.6:35951
distributed.worker - INFO -              nanny at:           172.18.0.6:37987
distributed.worker - INFO - Waiting to connect to:     tcp://172.18.0.4:36355
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  256.00 MB
distributed.worker - INFO -       Local Directory:       /tmp/worker-a0humvv5
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://172.18.0.4:36355
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
slurmstepd: error: *** JOB 2 ON c1 CANCELLED AT 2020-02-20T10:05:27 ***
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://172.18.0.6:37987'
distributed.nanny - WARNING - Worker process 135 was killed by unknown signal
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/opt/anaconda/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/anaconda/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/opt/anaconda/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
